apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: {name: hoodi, namespace: argocd}
spec:
  project: default
  source:
    repoURL: https://github.com/lejuho/hoodi-k8s.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: hoodi
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
